name: test

on: [push, pull_request]

permissions:
  contents: read

jobs:
  mod:
    runs-on: ubuntu-latest
    name: Check modules
    steps:
    - uses: actions/setup-go@v5
      with:
        go-version: 'oldstable'
    - uses: actions/checkout@v4
    - run: go mod tidy && git diff --exit-code go.mod go.sum
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        version: [ 'oldstable', 'stable' ]
    name: Go ${{ matrix.version }}
    steps:
    - uses: actions/setup-go@v5
      with:
        go-version: ${{ matrix.version }}
    - uses: actions/checkout@v4
    - run: go vet ./...
    - run: go test pkg/*
